version: '3.8'

services:
  web:
    image: 598130604507.dkr.ecr.eu-north-1.amazonaws.com/flask-mysql:latest
    ports:
      - "5000:5000"
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
